[Settings]
ID = "star-wars-browser"

# SPA routing with history pushState
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Redirect domain aliases to primary domain
[[redirects]]
  from = "https://starwars.benbooth.co/*"
  to = "https://starwars.benbooth.dev/:splat"
  status = 301
  force = true

# Optional: Redirect default Netlify subdomain to primary domain
[[redirects]]
  from = "https://star-wars-browser.netlify.com/*"
  to = "https://starwars.benbooth.dev/:splat"
  status = 301
  force = true
